#!/bin/bash

echo "Smart Baby Monitor - GitHub Push Options"
echo "========================================"
echo ""
echo "Your project has been prepared and emojis have been removed."
echo "The git repository has been initialized with all files committed."
echo ""
echo "Choose how you want to push to GitHub:"
echo ""
echo "Option 1: SSH (Recommended if you have SSH keys set up)"
echo "git remote set-url origin git@github.com:YuvDwi/Cradle.git"
echo "git push -u origin main"
echo ""
echo "Option 2: HTTPS with Personal Access Token"
echo "git remote set-url origin https://github.com/YuvDwi/Cradle.git"
echo "git push -u origin main"
echo "(You'll be prompted for your GitHub username and Personal Access Token)"
echo ""
echo "Option 3: GitHub CLI (if you have it installed)"
echo "gh auth login"
echo "git push -u origin main"
echo ""
echo "Option 4: Manual Repository Creation"
echo "1. Go to https://github.com/YuvDwi/Cradle"
echo "2. If it doesn't exist, create a new repository named 'Cradle'"
echo "3. Then run one of the above options"
echo ""
echo "Current git status:"
git status
echo ""
echo "Repository is ready to push!"
